name: deploy-docs

on:
  push:
    branches:
      - docs
    paths:
      - "docs/**"

jobs:
  deploy:
    name: Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - name: Connect over SSH
        env:
          SSH-KEY: ${{ secrets.SSH_KEY }}
        run: |
          ssh -i "$SSH-KEY" root@distillation.dev
