name: deploy

on:
  push:
    branches:
      - docs
    paths:
      - "docs/**"

jobs:
  deploy:
    name: Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "Bitch"
